# Generated by Django 4.0.3 on 2022-04-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('fechaPublicacion', models.DateTimeField(auto_now=True)),
                ('subtitulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaSubida', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('pie', models.CharField(max_length=300)),
                ('posteoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFoodBlog.posteo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaComentario', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(max_length=300)),
                ('posteoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFoodBlog.posteo')),
            ],
        ),
    ]
