# Generated by Django 4.0.3 on 2022-04-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodBlog', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='pie',
        ),
    ]
