# Generated by Django 4.0.3 on 2022-04-15 03:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodBlog', '0008_posteo_imagen_delete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
