# Generated by Django 4.0.3 on 2022-04-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodBlog', '0009_alter_posteo_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='posteoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppFoodBlog.posteo'),
        ),
    ]
