# Generated by Django 4.0.3 on 2022-04-20 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodBlog', '0010_alter_comentario_posteoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='fechaImagen',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
