# Generated by Django 4.0.3 on 2022-04-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodBlog', '0011_posteo_fechaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
