# Generated by Django 4.0.3 on 2022-04-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodBlog', '0013_alter_posteo_fechaimagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
