# Generated by Django 4.0.3 on 2022-04-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFoodUsers', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
